---
# Role to run Nginx in a docker container inside ubuntu instance

- include: install_docker.yml
  tags:
    - install_docker_ce


- name: Create Nginx Base directory on the host
  file:
    path: "{{ nginx_base_directory }}"
    state: 'directory'
    mode: '0755'

- name: Create Nginx Sites-enabled directory on the host
  file:
    path: "{{ nginx_base_directory }}/{{ nginx_sites_enabled_dir }}"
    state: 'directory'
    mode: '0755'

- name: Upload nginx.conf file in place
  copy:
    src: nginx.conf
    dest: "{{ nginx_base_directory }}/nginx.conf"
    mode: '0644'
#  notify: 'restart-docker-nginx'

- name: Upload vHost config in place
  copy:
    src: vhost01.conf
    dest: "{{ nginx_base_directory }}/{{ nginx_sites_enabled_dir }}/vhost01.conf"
    mode: '0644'
#  notify: 'restart-docker-nginx'

- name: Upload the static contect to be served by Nginx to the host"
  copy:
    src: version.txt
    dest: "{{ nginx_base_directory }}"
    mode: '0644'
#  notify: 'restart-docker-nginx'

- name: Start the nginx docker container
  docker_container:
    image: "nginx:{{ nginx_docker_tag }}"
    name: "{{ nginx_container_name }}"
    volumes: '{{ nginx_exposed_volumes }}'
    ports: '{{ nginx_published_ports }}'
    exposed_ports: '{{ nginx_exposed_ports }}'
    state: 'started'
    restart_policy: 'always'
    log_driver: 'syslog'
    log_options:
      tag: "{{ nginx_container_name }}"

