docker_version: 1.12

nginx_base_directory: '/opt/nginx'
nginx_sites_enabled_dir: "sites-enabled"

nginx_docker_tag: 'latest'
nginx_container_name: 'nginx'

nginx_exposed_ports:
  - '80'

nginx_published_ports:
  - '80:80'

nginx_exposed_volumes:
  - "{{ nginx_base_directory }}/nginx.conf:/etc/nginx/nginx.conf:ro"
  - "{{ nginx_base_directory }}/sites-enabled/:/etc/nginx/sites-enabled/:ro"
  - "{{ nginx_base_directory }}/sites-enabled/vhost01.conf:/etc/nginx/sites-enabled/vhost01.conf:ro"
  - "{{ nginx_base_directory }}/version.txt:/usr/share/nginx/html/version.txt:ro"
